version: "3.8"

services:
  app1:
    build: authorization-server
    container_name: auth_app
    volumes:
      - ./authorization-server:/go/src/
    ports:
      - 3160:50051
    depends_on:
      - db1
    extra_hosts:
      - "host.docker.internal:127.0.0.1"


  db1:
    build: authorization-server/.docker/postgres
    container_name: auth_db
    restart: always
    tty: true
    ports:
      - 3161:5432
    volumes:
      - ./authorization-server/.docker/postgres/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=authorizations
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisislocal-noneedtoworry
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  app2:
    build: payment-transaction
    container_name: transact_app
    volumes:
      - ./payment-transaction:/go/src/
    ports:
      - 3150:8000
    depends_on:
      - db2
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db2:
    build: payment-transaction/.docker/postgres
    container_name: transact_db
    restart: always
    tty: true
    ports:
      - 3151:5432
    volumes:
      - ./payment-transaction/.docker/postgres/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=transactions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisislocal-noneedtoworry
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
